version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: PeluContainer
    hostname: peluhost
    environment:
      - POSTGRES_DB=gestion_peluqueria_db
      - POSTGRES_USER=Franco
      - POSTGRES_PASSWORD=12345
    ports:
      - '5432:5432'
    volumes:
      - ./src/test/resources/db/volume:/var/lib/postgresql/data
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
